FROM php:5-apache

MAINTAINER Goon3r

# Install utils
RUN apt-get update \
    && apt-get install -y unzip curl nano git libmemcached-dev zlib1g-dev \
    && pecl install memcached-2.2.0 \
    && docker-php-ext-enable memcached

# Enable apache rewrite module
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/

# Download and install memcached
RUN curl -L https://github.com/elijaa/phpmemcachedadmin/archive/1.3.0.tar.gz -o /tmp/1.3.0.tar.gz \
    && tar xfz /tmp/1.3.0.tar.gz -C /tmp \
    && cp -r /tmp/phpmemcachedadmin-1.3.0/* /var/www/html/ \
    && rm  /var/www/html/Config/Memcache.sample.php

# Finalise / cleanup
RUN chown -R  www-data:www-data /var/www/html \
   &&  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*